name: CI

on:
    push:
        branches: [main]
    pull_request:
    merge_group:

jobs:
    build:
        name: Build and generate HTML
        runs-on: ubuntu-latest
        steps:
            - name: Install elan
              run: |
                  set -o pipefail
                  curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
                  ./elan-init -y --default-toolchain none
                  echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

            - uses: actions/checkout@v6

            - name: Compute short SHA
              id: shortSHA
              run: echo "short_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

            - name: Cache .lake
              uses: actions/cache@v5
              with:
                  path: .lake
                  key:
                      ${{ runner.os }}-${{ hashFiles('lake-manifest.json') }}-${{
                      hashFiles('lean-toolchain') }}-${{ steps.shortSHA.outputs.short_sha }}
                  restore-keys: |
                      ${{ runner.os }}-${{ hashFiles('lake-manifest.json') }}-${{ hashFiles('lean-toolchain') }}-

            - name: Lean version
              run: lean --version

            - name: Build
              run: lake build

            - name: Generate HTML
              run: lake exe generate-site

            - name: Upload site artifact
              uses: actions/upload-artifact@v7
              with:
                  name: site
                  path: _site

            - name: Upload site for PR deployment
              if: github.event_name == 'pull_request'
              uses: actions/upload-artifact@v7
              with:
                  name: site-for-deploy
                  path: _site
                  retention-days: 1

            - id: deploy-info
              name: Compute deployment metadata
              if: github.event_name != 'pull_request'
              run: |
                  set -e
                  echo "message=$(git log -1 --pretty=format:"%s")" >> "$GITHUB_OUTPUT"

            - name: Deploy to Netlify
              id: deploy
              uses: nwtgck/actions-netlify@v3.0
              if: github.event_name == 'push' && github.ref_name == 'main'
              with:
                  publish-dir: _site
                  production-branch: main
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  alias: ref-${{ github.ref_name }}
                  deploy-message:
                      "ref/${{ github.ref_name }}: ${{ steps.deploy-info.outputs.message }}"
                  enable-commit-comment: false
                  github-deployment-environment: verso-website-main
                  fails-without-credentials: true
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: "ffb7148a-a950-4fd1-9f49-758a8416bdbb"
